name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: configure cmake
        run: cmake -S . -B Build

      - name : build cmake
        run : cmake --Build .

      - name: Run tests
        run : .\Build\tests\test_runner.exe
        
